# Generated by Django 2.0 on 2018-05-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('url', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('topik', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('jumlah_kata', models.IntegerField()),
                ('rerata_rating', models.FloatField()),
            ],
            options={
                'db_table': 'berita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField()),
                ('jam', models.TimeField()),
                ('konten', models.CharField(max_length=100)),
                ('nama_user', models.CharField(max_length=50)),
                ('email_user', models.CharField(max_length=50)),
                ('url_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'komentar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NarasumberBerita',
            fields=[
                ('url_berita', models.ForeignKey(db_column='url_berita', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='berita.Berita')),
            ],
            options={
                'db_table': 'narasumber_berita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('url_berita', models.ForeignKey(db_column='url_berita', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='berita.Berita')),
                ('ip_address', models.CharField(max_length=100)),
                ('nilai', models.FloatField()),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('url_berita', models.ForeignKey(db_column='url_berita', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='berita.Berita')),
                ('id_riwayat', models.IntegerField()),
                ('waktu_revisi', models.DateTimeField()),
                ('konten', models.TextField()),
            ],
            options={
                'db_table': 'riwayat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('url_berita', models.ForeignKey(db_column='url_berita', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='berita.Berita')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
