# Generated by Django 2.0 on 2018-05-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Narasumber',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tempat', models.CharField(max_length=50)),
                ('tanggal', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=50)),
                ('jumlah_berita', models.IntegerField()),
                ('rerata_kata', models.IntegerField()),
            ],
            options={
                'db_table': 'narasumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('nomor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_bank', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rekening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universitas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('jalan', models.CharField(max_length=100)),
                ('kelurahan', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kodepos', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'universitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id_narasumber', models.ForeignKey(db_column='id_narasumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='akun.Narasumber')),
                ('nik_dosen', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dosen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id_narasumber', models.ForeignKey(db_column='id_narasumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='akun.Narasumber')),
                ('npm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mahasiswa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id_narasumber', models.ForeignKey(db_column='id_narasumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='akun.Narasumber')),
                ('nik_staf', models.CharField(max_length=20)),
                ('posisi', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'staf',
                'managed': False,
            },
        ),
    ]
