# Generated by Django 2.0 on 2018-05-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id_narasumber', models.ForeignKey(db_column='id_narasumber', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='akun.Narasumber')),
                ('tgl_diberikan', models.DateTimeField()),
                ('jumlah_berita', models.IntegerField()),
                ('jumlah_gaji', models.IntegerField()),
            ],
            options={
                'db_table': 'honor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_diberikan', models.DateTimeField()),
                ('tgl_kadaluarsa', models.DateTimeField()),
            ],
            options={
                'db_table': 'kupon',
                'managed': False,
            },
        ),
    ]
